// Intent Interview Session
// Generated by intent interview --cue

package intent

session: {
	id: "session-907C7B84-B8C8-6F1E-AE80-4DEBF2F6F50F"
	profile: "api"
	light_mode: false
	created_at: "2026-01-09T07:55:55.312-06:00"
	answers: []
	gaps: []
	conflicts: []
}
