// Intent Interview Session
// Generated by intent interview --cue

package intent

session: {
	id: "session-6E2CC8F4-DACB-C4E5-D85F-F809FA2B3F2A"
	profile: "api"
	light_mode: false
	created_at: "2026-01-09T06:55:39.779-06:00"
	answers: []
	gaps: []
	conflicts: []
}
