// Intent Interview Session
// Generated by intent interview --cue

package intent

session: {
	id: "session-8F29CEF5-4822-E7FF-451E-4A6DF3B0C50B"
	profile: "api"
	light_mode: true
	created_at: "2026-01-09T01:18:57.790-06:00"
	answers: []
	gaps: []
	conflicts: []
}
