// Intent Interview Session
// Generated by intent interview --cue

package intent

session: {
	id: "session-ADF5908A-E0D3-28F4-6DBA-3BB0C815B314"
	profile: "api"
	light_mode: false
	created_at: "2026-01-09T07:55:51.728-06:00"
	answers: []
	gaps: []
	conflicts: []
}
