// Intent Interview Session
// Generated by intent interview --cue

package intent

session: {
	id: "session-EBEAF6FD-C70F-3F0C-499B-4FEAB748F724"
	profile: "api"
	light_mode: false
	created_at: "2026-01-09T01:18:50.906-06:00"
	answers: []
	gaps: []
	conflicts: []
}
