/// Structured error handling for AI-friendly error recovery
///
/// This module provides structured errors with:
/// - Error type categorization for routing
/// - Machine-parseable context
/// - Actionable recovery steps
/// - Retry guidance
import gleam/dict.{type Dict}
import gleam/dynamic.{type DecodeError}
import gleam/io
import gleam/json.{type Json}
import gleam/list
import gleam/option.{type Option, None, Some}
import gleam/string
import intent/loader
import intent/security

/// Error type categories for routing and handling
pub type ErrorType {
  FileNotFound
  FilePermissionDenied
  CueValidationError
  CueExportError
  JsonParseError
  SpecParseError
  HttpConnectionError
  HttpTimeoutError
  HttpAuthError
  HttpServerError
  SecurityViolation
  CircularDependency
  SessionNotFound
  InvalidInput
  UnknownError
}

/// Structured error with recovery guidance
pub type StructuredError {
  StructuredError(
    error_type: ErrorType,
    message: String,
    context: Dict(String, String),
    suggestion: String,
    recovery: List(String),
    retry_allowed: Bool,
    exit_code: Int,
  )
}

/// Convert error type to string for JSON
pub fn error_type_to_string(et: ErrorType) -> String {
  case et {
    FileNotFound -> "file_not_found"
    FilePermissionDenied -> "file_permission_denied"
    CueValidationError -> "cue_validation_error"
    CueExportError -> "cue_export_error"
    JsonParseError -> "json_parse_error"
    SpecParseError -> "spec_parse_error"
    HttpConnectionError -> "http_connection_error"
    HttpTimeoutError -> "http_timeout_error"
    HttpAuthError -> "http_auth_error"
    HttpServerError -> "http_server_error"
    SecurityViolation -> "security_violation"
    CircularDependency -> "circular_dependency"
    SessionNotFound -> "session_not_found"
    InvalidInput -> "invalid_input"
    UnknownError -> "unknown_error"
  }
}

// =============================================================================
// Converters from Other Error Types
// =============================================================================

/// Convert loader LoadError to StructuredError
pub fn from_load_error(error: loader.LoadError, path: String) -> StructuredError {
  case error {
    loader.FileNotFound(_) -> file_not_found(path)
    loader.CueValidationFailed(error_path, _exit_code, stderr) ->
      cue_validation_error(stderr, error_path)
    loader.CueExportFailed(error_path, exit_code, stderr) ->
      StructuredError(
        error_type: CueExportError,
        message: "CUE export failed",
        context: dict.from_list([
          #("path", error_path),
          #("exit_code", string.inspect(exit_code)),
          #("stderr", stderr),
        ]),
        suggestion: "Check CUE syntax and ensure all required fields are present",
        recovery: [
          "Run: cue vet " <> error_path,
          "Verify spec field exists at top level",
          "Check for missing required fields",
          "Review CUE error message: " <> stderr,
        ],
        retry_allowed: True,
        exit_code: 3,
      )
    loader.JsonDecodeFailed(errors) -> {
      let error_summary = format_decode_errors(errors)
      StructuredError(
        error_type: JsonParseError,
        message: "JSON decoding failed",
        context: dict.from_list([#("errors", error_summary)]),
        suggestion: "Check JSON syntax generated by CUE export",
        recovery: [
          "Run: cue export " <> path,
          "Verify output is valid JSON",
          "Check decode errors: " <> error_summary,
        ],
        retry_allowed: False,
        exit_code: 3,
      )
    }
    loader.SpecParseFailed(errors) -> {
      let error_summary = format_decode_errors(errors)
      StructuredError(
        error_type: SpecParseError,
        message: "Spec structure parsing failed",
        context: dict.from_list([#("errors", error_summary)]),
        suggestion: "Ensure spec follows the required schema",
        recovery: [
          "Check spec.features array exists",
          "Verify all required fields are present",
          "Run: intent validate " <> path,
          "Review error: " <> error_summary,
        ],
        retry_allowed: True,
        exit_code: 3,
      )
    }
    loader.SecurityError(msg) ->
      StructuredError(
        error_type: SecurityViolation,
        message: msg,
        context: dict.from_list([#("path", path)]),
        suggestion: "Use safe file paths without shell metacharacters",
        recovery: [
          "Remove dangerous characters from path",
          "Use absolute paths when possible",
          "Avoid path traversal sequences (..)",
        ],
        retry_allowed: True,
        exit_code: 4,
      )
  }
}

/// Convert security SecurityError to StructuredError
pub fn from_security_error(
  error: security.SecurityError,
  path: String,
) -> StructuredError {
  case error {
    security.PathTraversalAttempt(_) ->
      StructuredError(
        error_type: SecurityViolation,
        message: "Path traversal attempt detected",
        context: dict.from_list([
          #("path", path),
          #("reason", "Contains .. or encoded traversal sequences"),
        ]),
        suggestion: "Use safe file paths without parent directory references",
        recovery: [
          "Remove .. from path", "Use absolute paths",
          "Avoid URL-encoded characters (%2e, %2f)",
        ],
        retry_allowed: True,
        exit_code: 4,
      )
    security.InvalidPath(_, reason) ->
      StructuredError(
        error_type: InvalidInput,
        message: "Invalid file path",
        context: dict.from_list([#("path", path), #("reason", reason)]),
        suggestion: "Provide a valid file path",
        recovery: ["Check path syntax", "Ensure path is not empty"],
        retry_allowed: True,
        exit_code: 4,
      )
    security.FileNotAccessible(_) -> file_not_found(path)
    security.UnsafeRegexPattern(pattern, reason) ->
      StructuredError(
        error_type: InvalidInput,
        message: "Unsafe regex pattern",
        context: dict.from_list([#("pattern", pattern), #("reason", reason)]),
        suggestion: "Use a safe regex pattern",
        recovery: ["Remove dangerous regex constructs", "Simplify pattern"],
        retry_allowed: True,
        exit_code: 4,
      )
    security.ShellMetacharactersDetected(_) ->
      StructuredError(
        error_type: SecurityViolation,
        message: "Shell metacharacters detected in path",
        context: dict.from_list([
          #("path", path),
          #("reason", "Contains ; | & $ ` > < or newlines"),
        ]),
        suggestion: "Remove shell metacharacters from path",
        recovery: [
          "Use only alphanumeric and basic path characters",
          "Avoid command injection characters",
        ],
        retry_allowed: True,
        exit_code: 4,
      )
    security.SymlinkNotAllowed(_) ->
      StructuredError(
        error_type: SecurityViolation,
        message: "Symlinks not allowed",
        context: dict.from_list([#("path", path)]),
        suggestion: "Use the actual file path instead of a symlink",
        recovery: ["Resolve symlink to real path", "Use direct file access"],
        retry_allowed: True,
        exit_code: 4,
      )
    security.SSRFAttempt(url, reason) -> security_violation(url, reason)
  }
}

// =============================================================================
// Common Error Builders
// =============================================================================

/// Build file not found error with recovery steps
pub fn file_not_found(path: String) -> StructuredError {
  StructuredError(
    error_type: FileNotFound,
    message: "File not found: " <> path,
    context: dict.from_list([
      #("path", path),
      #(
        "expected_location",
        "Spec files should be in project root or .interview/",
      ),
    ]),
    suggestion: "Check that the file path is correct and the file exists",
    recovery: [
      "Verify the file exists: ls " <> path,
      "Check file permissions: ls -la " <> path,
      "Use absolute path if relative path fails",
      "Ensure you're in the correct directory",
    ],
    retry_allowed: True,
    exit_code: 4,
  )
}

/// Build CUE validation error with line number if available
pub fn cue_validation_error(stderr: String, path: String) -> StructuredError {
  let line_number = extract_line_number(stderr)

  StructuredError(
    error_type: CueValidationError,
    message: "CUE validation failed",
    context: dict.from_list([
      #("path", path),
      #("cue_error", stderr),
      #("line", case line_number {
        Some(n) -> string.inspect(n)
        None -> "unknown"
      }),
    ]),
    suggestion: "Fix CUE syntax errors and try again",
    recovery: [
      "Check line "
        <> case line_number {
        Some(n) -> string.inspect(n)
        None -> "?"
      }
        <> " in "
        <> path,
      "Run: cue vet " <> path,
      "Ensure all fields have correct types",
      "Check for missing commas or braces",
    ],
    retry_allowed: True,
    exit_code: 3,
  )
}

/// Build HTTP connection error
pub fn http_connection_error(url: String, error_msg: String) -> StructuredError {
  StructuredError(
    error_type: HttpConnectionError,
    message: "Failed to connect to " <> url,
    context: dict.from_list([#("url", url), #("error", error_msg)]),
    suggestion: "Verify the service is running and accessible",
    recovery: [
      "Check service is running: curl " <> url,
      "Verify port is correct",
      "Check firewall rules",
      "Try with --allow-localhost if testing locally",
    ],
    retry_allowed: True,
    exit_code: 4,
  )
}

/// Build security violation error
pub fn security_violation(url: String, reason: String) -> StructuredError {
  StructuredError(
    error_type: SecurityViolation,
    message: "Security violation: " <> reason,
    context: dict.from_list([#("url", url), #("reason", reason)]),
    suggestion: "Use a public URL or enable localhost bypass for development",
    recovery: [
      "Use a public URL instead of private/internal addresses",
      "Add --allow-localhost flag for local development",
      "Set INTENT_ALLOW_LOCALHOST=true environment variable",
      "Verify the target URL is correct",
    ],
    retry_allowed: True,
    exit_code: 4,
  )
}

/// Build session not found error
pub fn session_not_found(session_id: String) -> StructuredError {
  StructuredError(
    error_type: SessionNotFound,
    message: "Session not found: " <> session_id,
    context: dict.from_list([
      #("session_id", session_id),
      #("sessions_path", ".interview/sessions.jsonl"),
    ]),
    suggestion: "List available sessions or start a new one",
    recovery: [
      "List sessions: intent sessions",
      "Start new session: intent interview --cue", "Check session ID spelling",
      "Verify .interview/ directory exists",
    ],
    retry_allowed: True,
    exit_code: 4,
  )
}

// =============================================================================
// JSON Encoding
// =============================================================================

/// Convert StructuredError to JSON
pub fn to_json(error: StructuredError) -> Json {
  json.object([
    #("action", json.string("error")),
    #(
      "error",
      json.object([
        #("type", json.string(error_type_to_string(error.error_type))),
        #("message", json.string(error.message)),
        #(
          "context",
          json.object(
            dict.to_list(error.context)
            |> list.map(fn(p) { #(p.0, json.string(p.1)) }),
          ),
        ),
      ]),
    ),
    #("suggestion", json.string(error.suggestion)),
    #("recovery", json.array(error.recovery, json.string)),
    #("retry_allowed", json.bool(error.retry_allowed)),
    #("exit_code", json.int(error.exit_code)),
  ])
}

/// Format error as human-readable text
pub fn format_text(error: StructuredError) -> String {
  let header =
    "Error (exit code "
    <> string.inspect(error.exit_code)
    <> "): "
    <> error.message
  let suggestion_text = "\nSuggestion: " <> error.suggestion
  let recovery_text =
    "\nRecovery Steps:\n"
    <> list.index_map(error.recovery, fn(step, idx) {
      "  " <> string.inspect(idx + 1) <> ". " <> step
    })
    |> string.join("\n")

  header <> suggestion_text <> recovery_text
}

/// Output error and halt with appropriate exit code
pub fn output_and_halt(error: StructuredError, is_json: Bool) -> Nil {
  case is_json {
    True -> {
      error
      |> to_json
      |> json.to_string
      |> io.println
      halt(error.exit_code)
    }
    False -> {
      error
      |> format_text
      |> io.println_error
      halt(error.exit_code)
    }
  }
}

// =============================================================================
// Helper Functions
// =============================================================================

/// Extract line number from CUE error message
fn extract_line_number(stderr: String) -> Option(Int) {
  // CUE errors typically have format: "file.cue:42:10: error message"
  // Try to extract the line number
  case string.split(stderr, ":") {
    [_, line_str, ..] ->
      case int.parse(string.trim(line_str)) {
        Ok(n) -> Some(n)
        Error(_) -> None
      }
    _ -> None
  }
}

/// Format decode errors for display
fn format_decode_errors(errors: List(DecodeError)) -> String {
  errors
  |> list.map(fn(err) {
    "Expected "
    <> err.expected
    <> " but found "
    <> err.found
    <> " at "
    <> string.join(err.path, ".")
  })
  |> string.join("; ")
}

/// Halt execution with exit code
@external(erlang, "intent_ffi", "halt")
fn halt(code: Int) -> Nil

// Required imports
import gleam/int
